#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Overall title for pages.
title: "Data and the FAIR Principles"

# Repository URL (without trailing slash).
repo: https://github.com/ReproNim/module-FAIR-data

# Root URL below username.github.io domain, with leading slash but no trailing slash.
# For example, for 'https://neurohackweek.github.io/lesson-example', use '/lesson-example'.
root: "/module-FAIR-data"

# Contact email address.
email: info@repronim.org

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Is this production or development? (Overridden in _config_dev.yml.)
is_production: true

# Sites.
repronim_site: "http://www.reproducibleimaging.org"
repronim_github: "https://github.com/ReproNim"
nhw_site: "https://neurohackweek.github.io"
nhw_github: "https://github.com/neurohackweek"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/swcarpentry/styles"
example_repo: "https://github.com/swcarpentry/lesson-example"
example_site: "https://swcarpentry.github.com/lesson-example"

# Start time in minutes (540 is 09:00 am)
start_time: 540

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn off built-in syntax highlighting.
highlighter: false
